# Generated by Django 4.2.11 on 2024-03-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_menu_options_menu_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id']},
        ),
    ]
