# Generated by Django 4.2.11 on 2024-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('is_author', models.BooleanField(default=False)),
            ],
        ),
    ]
