# Generated by Django 4.2.11 on 2024-03-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
