# Generated by Django 4.2.11 on 2024-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_article_tag_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_ids',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='content.tag'),
        ),
    ]
