# Generated by Django 4.2.11 on 2024-03-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.CharField(default='your_default_value_here', max_length=100),
        ),
    ]
